name = "ecofresh"
compatibility_date = "2024-01-01"

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"

[env.production]
name = "ecofresh"

[[env.production.routes]]
pattern = "ecofresh.pages.dev/*"
zone_name = "pages.dev"
